# Generated by Django 3.1 on 2020-09-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255)),
                ('cost_per_unit', models.FloatField(max_length=10)),
                ('units_available', models.IntegerField()),
                ('image_url', models.CharField(max_length=2084)),
            ],
        ),
    ]
