# Generated by Django 3.1 on 2020-09-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund_farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundfarm',
            name='units_available',
            field=models.IntegerField(),
        ),
    ]
