# Generated by Django 3.1 on 2020-09-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_farm', '0002_auto_20200908_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundfarm',
            name='roi_in_percent',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
