# Generated by Django 3.1 on 2020-09-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund_farm', '0004_auto_20200911_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundfarm',
            name='tenure_for_ROI',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
