# Generated by Django 3.1 on 2020-09-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_update', '0002_auto_20200924_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmupdate',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
