# Generated by Django 3.1 on 2020-09-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamrokheti_home', '0006_auto_20200911_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundfarm',
            name='roi_in_percent',
            field=models.IntegerField(max_length=3),
        ),
    ]
